import torch
import numpy as np
import os
import sys
import matplotlib.pyplot as plt
import seaborn as sns

sys.path.append(os.path.abspath(os.path.join(os.path.dirname(__file__), '../..')))
from backend.ml.cnn_pricer import ResidualSurfaceCNN
from backend.models.heston_pricer import heston_price
from backend.pricing.black_scholes import black_scholes_price

def generate_bucketed_surface(rho, nu, S=100.0, r=0.05, v0=0.04, theta=0.04, kappa=2.0):
    """
    Generates a Heston surface for a specific regime bucket (correlation and vol-of-vol).
    """
    grid_size = 16
    K_grid = np.linspace(S * 0.8, S * 1.2, grid_size)
    T_grid = np.linspace(0.1, 2.0, grid_size)
    
    K_mesh, T_mesh = np.meshgrid(K_grid, T_grid, indexing='ij')
    Moneyness = K_mesh / S
    
    Heston_price_mesh = heston_price(S, K_mesh, T_mesh, r, kappa, theta, nu, rho, v0, 'call')
    BS_price_mesh = black_scholes_price(S, K_mesh, T_mesh, r, np.sqrt(v0), 'call')
    
    return K_grid, T_grid, Moneyness, BS_price_mesh, Heston_price_mesh

def analyze_failure_modes():
    """
    Partitions Phase 5 errors by correlation (rho) and vol-of-vol (nu) buckets 
    to prove the CNN fails systematically across stochastic regimes.
    """
    device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')
    model_path = "backend/ml/cnn_phase5_heston.pth"
    
    if not os.path.exists(model_path):
        print(f"Error: Could not find Phase 5 model at {model_path}")
        return
        
    model = ResidualSurfaceCNN().to(device)
    model.load_state_dict(torch.load(model_path, map_location=device, weights_only=True))
    model.eval()

    # Define Regimes
    regimes = [
        {"name": "Strong Negative Skew (Equity-like)", "rho": -0.8, "nu": 0.4},
        {"name": "Mild Negative Skew", "rho": -0.3, "nu": 0.2},
        {"name": "Positive Skew (Commodity-like)", "rho": 0.5, "nu": 0.3}
    ]
    
    os.makedirs("experiments", exist_ok=True)
    report_path = "experiments/phase6_failure_analysis.txt"
    
    with open(report_path, "w") as f:
        f.write("Phase 6: Residual Learning Information Deficiency Analysis\n")
        f.write("=========================================================\n\n")
        
        plt.figure(figsize=(18, 6))
        
        for idx, regime in enumerate(regimes):
            rho = regime["rho"]
            nu = regime["nu"]
            
            K_grid, T_grid, Moneyness, BS_prices, Heston_prices = generate_bucketed_surface(rho=rho, nu=nu)
            
            # Inference
            X_tensor = torch.tensor(np.stack([BS_prices / 100.0, Moneyness, T_mesh:=np.meshgrid(K_grid, T_grid, indexing='ij')[1]], axis=0), dtype=torch.float32).unsqueeze(0).to(device)
            with torch.no_grad():
                preds_res_norm = model(X_tensor)
            CNN_res_price = BS_prices + preds_res_norm.squeeze().cpu().numpy() * 100.0
            
            # Error Calculation
            error = CNN_res_price - Heston_prices
            abs_error = np.abs(error)
            mae = np.mean(abs_error)
            mse = np.mean(error**2)
            
            # Logging
            report = f"[{regime['name']}] | rho={rho}, nu={nu}\n"
            report += f"  CNN MAE: {mae:.6f} | MSE: {mse:.6f}\n\n"
            print(report)
            f.write(report)
            
            # Plotting
            plt.subplot(1, 3, idx+1)
            vmax = np.max(abs_error) if np.max(abs_error) > 0 else 1.0
            sns.heatmap(abs_error, xticklabels=np.round(T_grid, 2), yticklabels=np.round(K_grid, 0), cmap='Reds', vmax=vmax)
            plt.title(f"{regime['name']}\nrho={rho}, nu={nu}")
            plt.xlabel("Maturity (T)")
            plt.ylabel("Strike (K)")
            
        plt.tight_layout()
        plt.savefig("experiments/phase6_regime_errors.png", dpi=300)
        plt.close()
        
        # 2. Information Deficiency Writeup
        deficiency_text = """
2. Information Deficiency Analysis
----------------------------------
Why did the model fail systematically? 
The CNN input space is defined strictly as a 3-channel state: [Moneyness (K/S), Maturity (T), Normalized BS Price].
Under a deterministic, time-invariant skew model (Phase 4), this state is a sufficient statistic to map the residual. 
However, under the Heston model, the residual surface is NOT Markovian in (K, T) alone. 

The Heston residual PDE is driven heavily by the correlation parameter (\rho) and the volatility of volatility (\nu).
Because \rho and \nu are NEVER passed to the CNN, the network is mathematically blind to the regime. 
It attempts to learn an 'average' correction across all random surfaces it sees during training, rather than a conditional correction.
Therefore, it structurally fails when evaluated on surfaces generated by aggressive parameter extremes.

3. Regime-Aware Design Proposal
-------------------------------
To generalize stochastic PDEs with ML, the system must become Regime-Aware.
Proposal: A 'Conditional Residual Corrector'.
- The input tensor must be expanded or conditioned on latent regime embeddings.
- (K/S, T) form the spatial grid.
- (\nu, \rho, v0, \kappa, \theta) must be injected densely into the network (e.g., via FiLM layers or concatenated channels).
This ensures the ML model behaves as a true parameterized PDE solver rather than a blind interpolator.

4. The Boundary of ML and Theory
--------------------------------
What should NEVER be learned by ML?
1. Exponential payoffs and asymptotic boundaries (Deep ITM/OTM bounds).
2. The fundamental martingale probability measures (P1, P2 integrations in Heston).
Theory must remain the dominant engine enforcing no-arbitrage bounds. ML is strictly relegated to fitting the structurally complex integrations that are computationally expensive in live environments.
"""
        f.write(deficiency_text)
        print("Saved detailed failure analysis to experiments/phase6_failure_analysis.txt and plots to experiments/phase6_regime_errors.png")

if __name__ == "__main__":
    analyze_failure_modes()
